"""initial schema

Revision ID: 2648e16dcc0e
Revises: 
Create Date: 2026-04-07 02:43:16.929676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2648e16dcc0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('startups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('stage', sa.Enum('pre_seed', 'seed', 'series_a', 'series_b', 'series_c', 'growth', name='startupstage'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'featured', name='startupstatus'), nullable=False),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('location_state', sa.String(length=100), nullable=True),
    sa.Column('location_country', sa.String(length=100), nullable=False),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('expert_score', sa.Float(), nullable=True),
    sa.Column('user_score', sa.Float(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('auth_provider', sa.Enum('google', 'linkedin', 'github', name='authprovider'), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'expert', 'superadmin', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('expert_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('application_status', sa.Enum('pending', 'approved', 'rejected', name='applicationstatus'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('startup_industries',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('startup_id', 'industry_id')
    )
    op.create_table('startup_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.Enum('article', 'linkedin_post', 'video', 'podcast', name='mediatype'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('startup_scores_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('score_type', sa.Enum('ai', 'expert_aggregate', 'user_aggregate', name='scoretype'), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.Column('dimensions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expert_industries',
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['expert_profiles.id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('expert_id', 'industry_id')
    )
    op.create_table('expert_skills',
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['expert_profiles.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('expert_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expert_skills')
    op.drop_table('expert_industries')
    op.drop_table('startup_scores_history')
    op.drop_table('startup_media')
    op.drop_table('startup_industries')
    op.drop_table('expert_profiles')
    op.drop_table('users')
    op.drop_table('startups')
    op.drop_table('skills')
    op.drop_table('industries')
    # ### end Alembic commands ###
